### PR TITLE
Remove restore key for the docker cache to reset it on reinit.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/69)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/69)* status: all files reviewed, 1 unresolved discussion (waiting on @bashash, @dzmitryhil, @miladz68, and @silverspase)

___
*[`.github/workflows/ci.yml` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/69#-NZ5NbHcBZs_6aWCxbxp:-NZ5NbHcBZs_6aWCxbxq:bo2ne23) ([raw file](https://github.com/CoreumFoundation/faucet/blob/4f3b3bbf08ed8f423f1e2a12410f930730ff2e57/.github/workflows/ci.yml#L87)):*
> ```YAML
>           key: ${{ runner.os }}-docker-${{ steps.get-year-week.outputs.date }} # year-week key
>           restore-keys: |
>             ${{ runner.os }}-docker-
> ```

what about the same thing for go cache?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/69)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bashash, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/69#-NZ5NbHcBZs_6aWCxbxp:-NZ5q-qL1Vp4YC1NPHgx:bw9rv27) ([raw file](https://github.com/CoreumFoundation/faucet/blob/4f3b3bbf08ed8f423f1e2a12410f930730ff2e57/.github/workflows/ci.yml#L87)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what about the same thing for go cache?
</blockquote></details>

For the go cache we don't need it IMO, it's small so it will use the base version as initial.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/69)* status: all files reviewed, 1 unresolved discussion (waiting on @bashash, @miladz68, and @silverspase)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/69)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bashash, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/69#-NZ5NbHcBZs_6aWCxbxp:-NZ6id489HgxAJNtX2Di:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/faucet/blob/4f3b3bbf08ed8f423f1e2a12410f930730ff2e57/.github/workflows/ci.yml#L87)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

For the go cache we don't need it IMO, it's small so it will use the base version as initial. 
</blockquote></details>

Updated.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/69)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash, @miladz68, and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/69)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash and @silverspase)

**Pull request merged**
