### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alinetskyi, @begmaroman, @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAOjUCDEs2qrYfAtzLt:-NAOjUCDEs2qrYfAtzLu:b8z1kpg) (no related file):*
Let's discuss it with @ysv after daily

___

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, and @ysv)

___
*[`Dockerfile` line 9 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAOu9ps784R6CKM3m07:-NAOu9ps784R6CKM3m08:bo5cn0j) ([raw file](https://github.com/coreumfoundation/faucet/blob/4df0743330c16110913774d06bd37c7c7434d8bf/Dockerfile#L9)):*
> ```Dockerfile
> RUN go mod download
> 
> COPY . .
> ```

What is the purpose to clone the mod first and then the entire project ?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 2 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 2 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, and @ysv)

___
*[`Dockerfile` line 9 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAOu9ps784R6CKM3m07:-NAP3o7e9Y5susGA7JPT:b-a13urs) ([raw file](https://github.com/coreumfoundation/faucet/blob/4df0743330c16110913774d06bd37c7c7434d8bf/Dockerfile#L9)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the purpose to clone the mod first and then the entire project ? 
</blockquote></details>

Have just understood, to cache the dependencies, the thread is resolved.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 2 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, and @ysv)

___
*[`Dockerfile` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAP9Zjj5yWfVMRKZgnI:-NAP9Zjj5yWfVMRKZgnJ:bem5n9a) ([raw file](https://github.com/coreumfoundation/faucet/blob/4df0743330c16110913774d06bd37c7c7434d8bf/Dockerfile#L14)):*
> ```Dockerfile
> 
> # Deploy Stage
> FROM alpine
> ```

Add `3.16` tag

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alinetskyi, @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`Dockerfile` line 9 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAOu9ps784R6CKM3m07:-NAPDkYr0v4NJl1BnN8u:bwoa1om) ([raw file](https://github.com/coreumfoundation/faucet/blob/4df0743330c16110913774d06bd37c7c7434d8bf/Dockerfile#L9)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Have just understood, to cache the dependencies, the thread is resolved.
</blockquote></details>

It is not resolved Dima, would you please resolve it ?
___
*[`Dockerfile` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAP9Zjj5yWfVMRKZgnI:-NAPEBKE7UBPrmjboONK:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/4df0743330c16110913774d06bd37c7c7434d8bf/Dockerfile#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Add `3.16` tag
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 1 unresolved discussion (waiting on @alinetskyi, @begmaroman, @dzmitryhil, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 8 unresolved discussions (waiting on @alinetskyi, @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`Dockerfile` line 5 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAQ0Ytu0LROWOY6pdla:-NAQ0Ytu0LROWOY6pdlb:b-ulk9aw) ([raw file](https://github.com/coreumfoundation/faucet/blob/4a7e3c80f54b1c111a8ce0ac8b660280f2d18e57/Dockerfile#L5)):*
> ```Dockerfile
> 
> WORKDIR /app
> COPY go.mod ./
> ```

Minor: ./ -> .
___
*[`Dockerfile` line 11 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAPzv4N8tANCam-KQbW:-NAPzv4O2h1c6MMFNKMY:b3ryfsr) ([raw file](https://github.com/coreumfoundation/faucet/blob/4a7e3c80f54b1c111a8ce0ac8b660280f2d18e57/Dockerfile#L11)):*
> ```Dockerfile
> COPY . .
> 
> RUN go build -o /bin/faucet
> ```

you could set CGO_ENABLED=0, personally I don't like to compile with cgo enabled if it's not really needed
___
*[`Dockerfile` line 11 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAQ-69sDXxY4zT7VeD3:-NAQ-69sDXxY4zT7VeD4:biobh1w) ([raw file](https://github.com/coreumfoundation/faucet/blob/4a7e3c80f54b1c111a8ce0ac8b660280f2d18e57/Dockerfile#L11)):*
> ```Dockerfile
> COPY . .
> 
> RUN go build -o /bin/faucet
> ```

add `-trimpath` flag to remove directory from paths in call stacks
___
*[`Dockerfile` line 11 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAQ-Q5iCMfxkEJjJIKk:-NAQ-Q5iCMfxkEJjJIKl:b-1udg1m) ([raw file](https://github.com/coreumfoundation/faucet/blob/4a7e3c80f54b1c111a8ce0ac8b660280f2d18e57/Dockerfile#L11)):*
> ```Dockerfile
> COPY . .
> 
> RUN go build -o /bin/faucet
> ```

Minor: consider adding `-ldflags="-w -s"` to remove debugging symbols which should reduce the size of the binary
___
*[`Dockerfile` line 14 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAQ-2g644jxXDVhV6d6:-NAQ-2g644jxXDVhV6d7:b-61ncp0) ([raw file](https://github.com/coreumfoundation/faucet/blob/4a7e3c80f54b1c111a8ce0ac8b660280f2d18e57/Dockerfile#L14)):*
> ```Dockerfile
> 
> # Deploy Stage
> FROM alpine:3.16
> ```

once cgo is disabled you may use `scratch` here
___
*[`Dockerfile` line 16 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAQ-ddjBjhDDbxA_wZY:-NAQ-ddjBjhDDbxA_wZZ:beob7s6) ([raw file](https://github.com/coreumfoundation/faucet/blob/4a7e3c80f54b1c111a8ce0ac8b660280f2d18e57/Dockerfile#L16)):*
> ```Dockerfile
> FROM alpine:3.16
> 
> WORKDIR /
> ```

isn't it by default?
___
*[`Dockerfile` line 21 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAQ00YJ6zcYsrvNiISN:-NAQ00YK5iucFij5La7j:bm4m4ho) ([raw file](https://github.com/coreumfoundation/faucet/blob/4a7e3c80f54b1c111a8ce0ac8b660280f2d18e57/Dockerfile#L21)):*
> ```Dockerfile
> 
> EXPOSE 8090
> ```

faucet requires private key mounted inside container so `VOLUME` should be specified

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 6 unresolved discussions (waiting on @alinetskyi, @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`Dockerfile` line 11 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAPzv4N8tANCam-KQbW:-NAQRHX04dM95fx75IqU:b-jgsdt7) ([raw file](https://github.com/coreumfoundation/faucet/blob/4a7e3c80f54b1c111a8ce0ac8b660280f2d18e57/Dockerfile#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you could set CGO_ENABLED=0, personally I don't like to compile with cgo enabled if it's not really needed
</blockquote></details>

nvm, after upgrading coreum faucet requires cgo (because of wasm)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 7 unresolved discussions (waiting on @alinetskyi, @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`Dockerfile` line 11 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAU7rvnA6DMe7SwxxMY:-NAU7rvo1stYLdcuZFob:b-vkimwk) ([raw file](https://github.com/coreumfoundation/faucet/blob/4a7e3c80f54b1c111a8ce0ac8b660280f2d18e57/Dockerfile#L11)):*
> ```Dockerfile
> COPY . .
> 
> RUN go build -o /bin/faucet
> ```

After wasm is integrated into coreum it is required to build faucet in much more tricky way:
- additional tag must be added: https://github.com/CoreumFoundation/crust/blob/znet-faucet/build/build.go#L61
- static linking must be enabled: https://github.com/CoreumFoundation/crust/blob/znet-faucet/build/golang/go.go#L217
- wasm library must be installed inside the building image: https://github.com/CoreumFoundation/crust/blob/znet-faucet/build/tools/tools.go#L110

That's why I highly recommend to reuse the logic already built into crust, to not apply stackoverflow-driven development (copy-paste) which would require managing the same tricky magic in many places. That was the original idea: write this logic once for all the people in the team. Compiling our software correctly is not a trivial task.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 6 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 4 unresolved discussions (waiting on @alinetskyi, @begmaroman, @wojtek-coreum, and @ysv)

___
*[`Dockerfile` line 11 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAQ-69sDXxY4zT7VeD3:-NAcMnkx80WxdbIMLjNV:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/4a7e3c80f54b1c111a8ce0ac8b660280f2d18e57/Dockerfile#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

add `-trimpath` flag to remove directory from paths in call stacks
</blockquote></details>

Done.
___
*[`Dockerfile` line 11 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAU7rvnA6DMe7SwxxMY:-NAdSHI3ACJbP5fp2R6y:b-3orpce) ([raw file](https://github.com/coreumfoundation/faucet/blob/4a7e3c80f54b1c111a8ce0ac8b660280f2d18e57/Dockerfile#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

After wasm is integrated into coreum it is required to build faucet in much more tricky way:
- additional tag must be added: https://github.com/CoreumFoundation/crust/blob/znet-faucet/build/build.go#L61
- static linking must be enabled: https://github.com/CoreumFoundation/crust/blob/znet-faucet/build/golang/go.go#L217
- wasm library must be installed inside the building image: https://github.com/CoreumFoundation/crust/blob/znet-faucet/build/tools/tools.go#L110

That's why I highly recommend to reuse the logic already built into crust, to not apply stackoverflow-driven development (copy-paste) which would require managing the same tricky magic in many places. That was the original idea: write this logic once for all the people in the team. Compiling our software correctly is not a trivial task.
</blockquote></details>

Done.
It indeed was a chore to get everything right.
___
*[`Dockerfile` line 16 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAQ-ddjBjhDDbxA_wZY:-NAcNEFd7egrsuMUUhsH:b-yiuei5) ([raw file](https://github.com/coreumfoundation/faucet/blob/4a7e3c80f54b1c111a8ce0ac8b660280f2d18e57/Dockerfile#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

isn't it by default?
</blockquote></details>

It is by default, just being explicit
___
*[`Dockerfile` line 21 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAQ00YJ6zcYsrvNiISN:-NAcgkcB2-V53c0dPY1O:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/4a7e3c80f54b1c111a8ce0ac8b660280f2d18e57/Dockerfile#L21)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

faucet requires private key mounted inside container so `VOLUME` should be specified
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 3 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, and @ysv)

___
*[`Dockerfile` line 2 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdUoXp-H8FyLZzRmqu:-NAdUoXp-H8FyLZzRmqv:bk2d173) ([raw file](https://github.com/coreumfoundation/faucet/blob/546bccabc1c86a39ec612d78d8802a8c22f92db2/Dockerfile#L2)):*
> ```Dockerfile
> # Build Stage
> FROM golang:1.19-alpine3.16 AS builder
> ```

To be discussed: `builder` container is the perfect example of code duplication. Whatever is coded here has been already done by crust.
We could use `crust build/faucet` and copy `bin/.cache/faucet` file into `alpine` image. `znet` does exactly that, but it mounts bin inside `alpine` instead of building new image. But `crust` could build entire final image and `znet` could use it. There ar two obvious pros of doing this:
- code for generating binaries and docker image is reused by znet and prod deployment
- prod uses the same docker image which was tested by CI in znet, meaning that we test prod image on every PR
- no way to create a situation where CI passes but deployed infra does not build or work

As @miladz68 said it was a tricky thing to arrange this dockerfile, so it's yet another argument for sharing the common way of doing this between us and devops department.
___
*[`Dockerfile` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdUDuO85ajPNuezoVC:-NAdUDuP-1TWtOuZZ9m5:b-2w3x8a) ([raw file](https://github.com/coreumfoundation/faucet/blob/546bccabc1c86a39ec612d78d8802a8c22f92db2/Dockerfile#L10)):*
> ```Dockerfile
> RUN curl -L https://github.com/CosmWasm/wasmvm/releases/download/v1.0.0/libwasmvm_muslc.x86_64.a -o /lib/libwasmvm_muslc.x86_64.a
> RUN sha256sum /lib/libwasmvm_muslc.aarch64.a | grep 7d2239e9f25e96d0d4daba982ce92367aacf0cbd95d2facb8442268f2b1cc1fc
> RUN sha256sum /lib/libwasmvm_muslc.x86_64.a | grep f6282df732a13dec836cda1f399dd874b1e3163504dbd9607c6af915b2740479
> ```

I believe `x86_64` is the only architecture we must support. Is this docker image for anything else than deploying faucet to our kubernetes cluster?
___
*[`Dockerfile` line 30 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdTsKi2X8zb-gzKwP2:-NAdTsKi2X8zb-gzKwP3:bq917uv) ([raw file](https://github.com/coreumfoundation/faucet/blob/546bccabc1c86a39ec612d78d8802a8c22f92db2/Dockerfile#L30)):*
> ```Dockerfile
> WORKDIR /
> 
> VOLUME /data
> ```

It requires only key file to be mounted, not entire folder so `/data/private_keys_unarmored_hex.txt`

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 3 unresolved discussions (waiting on @alinetskyi, @begmaroman, @wojtek-coreum, and @ysv)

___
*[`Dockerfile` line 2 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdUoXp-H8FyLZzRmqu:-NAdd9NF3WD9QUtu_GHK:b-y5vcyo) ([raw file](https://github.com/coreumfoundation/faucet/blob/546bccabc1c86a39ec612d78d8802a8c22f92db2/Dockerfile#L2)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

To be discussed: `builder` container is the perfect example of code duplication. Whatever is coded here has been already done by crust.
We could use `crust build/faucet` and copy `bin/.cache/faucet` file into `alpine` image. `znet` does exactly that, but it mounts bin inside `alpine` instead of building new image. But `crust` could build entire final image and `znet` could use it. There ar two obvious pros of doing this:
- code for generating binaries and docker image is reused by znet and prod deployment
- prod uses the same docker image which was tested by CI in znet, meaning that we test prod image on every PR
- no way to create a situation where CI passes but deployed infra does not build or work

As @miladz68 said it was a tricky thing to arrange this dockerfile, so it's yet another argument for sharing the common way of doing this between us and devops department.
</blockquote></details>

I understand the point, and as I mentioned it was not simple to generate this Dockerfile. however I also understand that we prefer repos to be self contained and deliver their own Dockerfiles. I have no preference here and it seems Devops related and we should observe their preference here. @ysv care to comment ?
___
*[`Dockerfile` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdUDuO85ajPNuezoVC:-NAdcxAfE1rrcgt0HuSM:b-f6q52v) ([raw file](https://github.com/coreumfoundation/faucet/blob/546bccabc1c86a39ec612d78d8802a8c22f92db2/Dockerfile#L10)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I believe `x86_64` is the only architecture we must support. Is this docker image for anything else than deploying faucet to our kubernetes cluster?
</blockquote></details>

I think that will be the only architecture that will be used for deployments, but other developers might be tasked to modify this file. 
___
*[`Dockerfile` line 30 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdTsKi2X8zb-gzKwP2:-NAdcne58d-ognj0792Q:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/546bccabc1c86a39ec612d78d8802a8c22f92db2/Dockerfile#L30)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It requires only key file to be mounted, not entire folder so `/data/private_keys_unarmored_hex.txt`
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 1 unresolved discussion (waiting on @alinetskyi, @begmaroman, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 4 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`Dockerfile` line 30 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdTsKi2X8zb-gzKwP2:-NAdxKwk-u0n3d9UpUPv:bf0u2w6) ([raw file](https://github.com/coreumfoundation/faucet/blob/546bccabc1c86a39ec612d78d8802a8c22f92db2/Dockerfile#L30)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I was always wondering what is the reason of specifying VOLUME in Dockerfile directly ?
Because you still need to mount it on container start `docker run -v ...` independently on specifying it here
</blockquote></details>

It's an indicator for user that volume must be mounted for image tow ork correctly

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 3 unresolved discussions (waiting on @alinetskyi, @begmaroman, @wojtek-coreum, and @ysv)

___
*[`Dockerfile` line 2 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdUoXp-H8FyLZzRmqu:-NAhKKS_DkhCpiMaNugR:b-kq29db) ([raw file](https://github.com/coreumfoundation/faucet/blob/546bccabc1c86a39ec612d78d8802a8c22f92db2/Dockerfile#L2)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets discuss after daily
</blockquote></details>

I think it might be reasonable to have crust generate the docker file and copy it here, so we don't have to manually manage it. 
Or have crust generate the docker file and let devops team generate Dockerfile on demand. 
___
*[`Dockerfile` line 10 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdkBWSBEJ8FcrXAdcJ:-NAhJpTH1kvOK404z3b_:b-aq3v05) ([raw file](https://github.com/coreumfoundation/faucet/blob/e03c5ffd12bd60fc745fae48256ca90cdc399229/Dockerfile#L10)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I always try to merge these type of command sequences which are doing a single thing as result
Because it creates less docker cace layers and makes image lighter, faster to build
</blockquote></details>

I prefer not to do it here since commands are too long already, hopefully we will remove this after client refactor. 
___
*[`Dockerfile` line 18 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdkkdX0kL8Sj14WdjC:-NAhJysI5DXeNOZ24vgb:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/e03c5ffd12bd60fc745fae48256ca90cdc399229/Dockerfile#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

isn't it possible to make a single `COPY go.mod go.sum .` ?
https://docs.docker.com/engine/reference/builder/#copy
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: all files reviewed, 3 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, and @ysv)

___
*[`Dockerfile` line 2 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdUoXp-H8FyLZzRmqu:-NAhj5cf7nY88RWMo-wX:bgrfz4c) ([raw file](https://github.com/coreumfoundation/faucet/blob/546bccabc1c86a39ec612d78d8802a8c22f92db2/Dockerfile#L2)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think it might be reasonable to have crust generate the docker file and copy it here, so we don't have to manually manage it. 
Or have crust generate the docker file and let devops team generate Dockerfile on demand. 
</blockquote></details>

Or let `crust` build the final docker image, test it in `znet` and make everyone's life easier :-)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alinetskyi and @begmaroman)

___
*[`Dockerfile` line 2 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdUoXp-H8FyLZzRmqu:-NAivX2c21M6hEDuNo-q:bk8280d) ([raw file](https://github.com/coreumfoundation/faucet/blob/546bccabc1c86a39ec612d78d8802a8c22f92db2/Dockerfile#L2)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Or let `crust` build the final docker image, test it in `znet` and make everyone's life easier :-)
</blockquote></details>

lets keep it as it is
I don't want to put more on crust before we rewise it 
Later we might change but the current approach is ok
___
*[`Dockerfile` line 30 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdTsKi2X8zb-gzKwP2:-NAiwnc10yTArHqKHGl0:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/546bccabc1c86a39ec612d78d8802a8c22f92db2/Dockerfile#L30)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's an indicator for user that volume must be mounted for image tow ork correctly
</blockquote></details>

ok
___
*[`Dockerfile` line 10 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/3#-NAdkBWSBEJ8FcrXAdcJ:-NAivndjES7s3Ym5z_AJ:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/e03c5ffd12bd60fc745fae48256ca90cdc399229/Dockerfile#L10)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I prefer not to do it here since commands are too long already, hopefully we will remove this after client refactor. 
</blockquote></details>

ok

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alinetskyi and @begmaroman)

**Pull request merged**
