### PR TITLE
Rename coreum-address to coreum-grpc address in the transfer_test.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/67)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/67#-:-NXBD34c-JWG7mv8T3WE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash, @silverspase, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash and @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash and @silverspase)

**Pull request merged**
