### PR TITLE
Limit rate of fund requests per IP

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/http/http.go` line 30 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGasFaD2RQsYBvIkIRH:-NGasFaE6fU-inwauKUI:b-lra823) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/pkg/http/http.go#L30)):*
> ```Go
> 
> // New returns a server instance
> func New(log *zap.Logger, m ...MiddlewareFunc) Server {
> ```

`m` isn't the best name here.
___
*[`pkg/http/http.go` line 96 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGasVpy9RLpYT4FsX8Y:-NGasVpy9RLpYT4FsX8Z:br5xl0u) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/pkg/http/http.go#L96)):*
> ```Go
> 			exitListening <- err
> 		}()
> 		err = s.limiter.Run(ctx)
> ```

I don't get that logic here you set the error and don't use it
___
*[`pkg/http/http.go` line 120 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGasqvg1stMJd8Ln7e6:-NGasqvg1stMJd8Ln7e7:b4c5kyb) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/pkg/http/http.go#L120)):*
> ```Go
> }
> 
> func reopenCtx(ctx context.Context) context.Context {
> ```

Could you elaborate on the context, and why it's needed?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/http/http.go` line 96 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGasVpy9RLpYT4FsX8Y:-NGaygmS-TZRveN7_Vox:b-1sm4xm) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/pkg/http/http.go#L96)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't get that logic here you set the error and don't use it
</blockquote></details>

it's used in `defer`. Welcome to the world of broken parallelism design we decided to use for some reason I don't understand :-)
___
*[`pkg/http/http.go` line 120 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGasqvg1stMJd8Ln7e6:-NGaytjg4PQ24sa7NLVx:byagdhq) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/pkg/http/http.go#L120)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you elaborate on the context, and why it's needed?
</blockquote></details>

In the place where it is used ctx is canceled. To support graceful shutdown ctx must be "decanceled". Bad way of doing this is by creating new context with `context.Background()` which doesn't contain all the configured stuff (logger in our case). Betetr approach is to just ignore the fact that parent ctx is canceled.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`http/errors.go` line 84 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGqAMT623xrHY7bUgVe:-NGqAMT623xrHY7bUgVf:bgvzizr) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/http/errors.go#L84)):*
> ```Go
> 		app.ErrInvalidAddressFormat:     newSingleAPIError("address.invalid", app.ErrInvalidAddressFormat.Error(), stdHttp.StatusNotAcceptable),
> 		app.ErrUnableToTransferToken:    newSingleAPIError("server.internal_error", app.ErrUnableToTransferToken.Error(), stdHttp.StatusInternalServerError),
> 		http.ErrRateLimitExhausted:      newSingleAPIError("server.rate_limit", http.ErrRateLimitExhausted.Error(), stdHttp.StatusForbidden),
> ```

429 Too Many Requests is a better option than Forbidden 
___
*[`pkg/http/errors.go` line 6 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGpy4828KjwtYl-cNL_:-NGpy4838oOpIQBZRXa1:b-2zgskl) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/pkg/http/errors.go#L6)):*
> ```Go
> 
> // ErrRateLimitExhausted is returned when rate limit is exhausted for an IP address
> var ErrRateLimitExhausted = errors.New("rate limit exhausted")
> ```

I know that this is confusing, but this error definition should go to the http folder in the root
___
*[`pkg/http/limiter.go` line 69 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGq8bxl8Rnk5qSn2nMl:-NGq8bxl8Rnk5qSn2nMm:ble35vo) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/pkg/http/limiter.go#L69)):*
> ```Go
> 	defer l.mu.Unlock()
> 
> 	return l.previous.GetProportionally(ip)+l.current.Increment(ip) <= l.limit
> ```

you should not increment if the the request is not allowed. 



_Code quote:_
```Go
https://blog.cloudflare.com/counting-things-a-lot-of-different-things/
```

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGuVQZf1eW_yD5x16z1:-NGuVQZf1eW_yD5x16z2:bnby9f7) (no related file):*
You might kill me but when trying to move limiter to another `http` scope I realized that I need to introduce nested goroutines (in both `http` packages). I really tried to do it the native way but after a while I realized that I'm reimplementing `parallel` to sunc them. So instead of reimplementing it, I just decided to use it `directly`.

___
___
*[`http/errors.go` line 84 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGqAMT623xrHY7bUgVe:-NGuIg2q7jZOlzW7NzbN:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/http/errors.go#L84)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

429 Too Many Requests is a better option than Forbidden 
</blockquote></details>

Done.
___
*[`pkg/http/http.go` line 30 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGasFaD2RQsYBvIkIRH:-NGuRZUj9UttCN3aQ6vs:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/pkg/http/http.go#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`m` isn't the best name here.
</blockquote></details>

Done.
___
*[`pkg/http/errors.go` line 6 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGpy4828KjwtYl-cNL_:-NGuRYE_Ax8AEuO1X7v3:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/pkg/http/errors.go#L6)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I know that this is confusing, but this error definition should go to the http folder in the root
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/http/limiter.go` line 69 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGq8bxl8Rnk5qSn2nMl:-NGuYQCD1T77PGU8RbJW:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/pkg/http/limiter.go#L69)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you should not increment if the the request is not allowed. 
</blockquote></details>

Done.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGuVQZf1eW_yD5x16z1:-NGucbIE9axCF3T6whdX:b-blxahh) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You might kill me but when trying to move limiter to another `http` scope I realized that I need to introduce nested goroutines (in both `http` packages). I really tried to do it the native way but after a while I realized that I'm reimplementing `parallel` to sunc them. So instead of reimplementing it, I just decided to use it `directly`.
</blockquote></details>

The problematic part here, is that there are not much guys, who knows it, so the quality of the review can be good enough.

___

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> Reviewed 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGuVQZf1eW_yD5x16z1:-NGudiWKDCFXd_bZYfpW:b-r8amp8) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The problematic part here, is that there are not much guys, who knows it, so the quality of the review can be good enough.
</blockquote></details>

@ysv you should leave your comment. 
I personally think that parallel package provides some improvement at the cost of departing from standard go way. I am neither for nor against as opposed in the past that I was against it. 

___

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 6 unresolved discussions (waiting on @wojtek-coreum)

___
*[`http/http.go` line 26 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHP31HK2YuM1LiAoPWQ:-NHP31HK2YuM1LiAoPWR:blu6um0) ([raw file](https://github.com/coreumfoundation/faucet/blob/f46133945a5f494c623852dc2e57a4acb73b668f/http/http.go#L26)):*
> ```Go
> // New returns an instance of the HTTP type
> func New(app app.App, log *zap.Logger) HTTP {
> 	limiter := NewWeightedWindowLimiter(2, time.Hour)
> ```

I suggest to make this configurable from flags/envs so we never return back to it
Shouldn't take much effort to do, isn't it ?

See next comment on details how I see initialization
___
*[`http/http.go` line 49 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHOx0PwB0UCo2vS3PDz:-NHOx0PxDHjkzr5guWwi:bhdc758) ([raw file](https://github.com/coreumfoundation/faucet/blob/f46133945a5f494c623852dc2e57a4acb73b668f/http/http.go#L49)):*
> ```Go
> 			return h.server.Start(ctx, address, 30*time.Second)
> 		})
> 		spawn("limiterCleanup", parallel.Fail, h.limiter.Run)
> ```

IMO limiter should be initialized in main.go ^ cleanup routine should be started in main.go before HTTP server initialization
It is not part of HTTP server logic but sort of custom business logic so i suggest to move it to main.go. It also makes it possible to configure it using flags/envs etc

In the same way we put `batcher.Start & New` in main.go because it is part of batcher initialization not HTTP
___
*[`pkg/http/http.go` line 120 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGasqvg1stMJd8Ln7e6:-NHP1t7rDD0HqvpUuwwU:bi9si6n) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/pkg/http/http.go#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

In the place where it is used ctx is canceled. To support graceful shutdown ctx must be "decanceled". Bad way of doing this is by creating new context with `context.Background()` which doesn't contain all the configured stuff (logger in our case). Betetr approach is to just ignore the fact that parent ctx is canceled.
</blockquote></details>

took me some time to understand the concept here
Can you add a comment on top of `reopened struct`
___
*[`pkg/http/http.go` line 104 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHP2TEC2EHrjnMG_aPW:-NHP2TEC2EHrjnMG_aPX:biqxfkg) ([raw file](https://github.com/coreumfoundation/faucet/blob/f46133945a5f494c623852dc2e57a4acb73b668f/pkg/http/http.go#L104)):*
> ```Go
> }
> 
> type reopened struct {
> ```

non-blocking:
I suggest to rename this struct to `reopenedCtx` and initialization to `newReopenedCtx`
___
*[`http/limiter.go` line 6 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHOwoMn4Ax9qA5OVzEd:-NHOwoMq9Pi2c4IIZWyU:b-e637fw) ([raw file](https://github.com/coreumfoundation/faucet/blob/f46133945a5f494c623852dc2e57a4acb73b668f/http/limiter.go#L6)):*
> ```Go
> 	"context"
> 	"net"
> 	stdHTTP "net/http"
> ```

`nethttp` / `stdhttp` ?
It is better to not use uppercase on pkg imports

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 6 unresolved discussions (waiting on @wojtek-coreum)

___
*[`http/http.go` line 26 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHP31HK2YuM1LiAoPWQ:-NHP3lwE74GYBRR_XE3w:b4mkel9) ([raw file](https://github.com/coreumfoundation/faucet/blob/f46133945a5f494c623852dc2e57a4acb73b668f/http/http.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I suggest to make this configurable from flags/envs so we never return back to it
Shouldn't take much effort to do, isn't it ?

See next comment on details how I see initialization
</blockquote></details>

The best way of passing limit I see currently: 
`--ip-rate-limit=2/1h` - 2 requests per hour
`--ip-rate-limit=5/24h` - 5 requests per day

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGuVQZf1eW_yD5x16z1:-NHP4OH292XKxrpt3ALM:b-l7bzcc) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I believe that @miladz68 and @ysv understand the idea and the interface, they probably didn't review the internals. If you don't understand sth by reading examples and/or doc I'm happy to explain. I may tolerate native `go` for trivial cases when goroutines are started next to each other but in case of nested goroutines started by different components in different scope I don't want to deal with different mechanism of syncing them each time.
</blockquote></details>

I'm ok with parallel 
Would be nice to improve interface exposed by it so it doesn't look like "framework" but I'm ok with it

___

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68)

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 5 unresolved discussions (waiting on @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: 4 of 13 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`http/http.go` line 26 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHP31HK2YuM1LiAoPWQ:-NHTF9xr50G6P9CLgVK4:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/f46133945a5f494c623852dc2e57a4acb73b668f/http/http.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

The best way of passing limit I see currently: 
`--ip-rate-limit=2/1h` - 2 requests per hour
`--ip-rate-limit=5/24h` - 5 requests per day
</blockquote></details>

Done.
___
*[`http/http.go` line 49 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHOx0PwB0UCo2vS3PDz:-NHTNepd3Q22ZWF9iyyU:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/f46133945a5f494c623852dc2e57a4acb73b668f/http/http.go#L49)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO limiter should be initialized in main.go ^ cleanup routine should be started in main.go before HTTP server initialization
It is not part of HTTP server logic but sort of custom business logic so i suggest to move it to main.go. It also makes it possible to configure it using flags/envs etc

In the same way we put `batcher.Start & New` in main.go because it is part of batcher initialization not HTTP
</blockquote></details>

Done.
___
*[`pkg/http/http.go` line 120 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NGasqvg1stMJd8Ln7e6:-NHTOeu1EtJt_MeZo_8W:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/1bf869fa562d975c0a89ed0b4d5caec30653648c/pkg/http/http.go#L120)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

took me some time to understand the concept here
Can you add a comment on top of `reopened struct`
</blockquote></details>

Done.
___
*[`http/limiter.go` line 6 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHOwoMn4Ax9qA5OVzEd:-NHTO4kE4epuq8HcrWXp:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/f46133945a5f494c623852dc2e57a4acb73b668f/http/limiter.go#L6)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`nethttp` / `stdhttp` ?
It is better to not use uppercase on pkg imports
</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum)

___
*[`main.go` line 114 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHVEC7PA_mVqDgI4Zcp:-NHVEC7PA_mVqDgI4Zcq:bp7xpga) ([raw file](https://github.com/coreumfoundation/faucet/blob/2cfdd742c535fb71c9fe09115cbb93bbe7fb2825/main.go#L114)):*
> ```Go
> 	)
> 
> 	err = parallel.Run(ctx, func(ctx context.Context, spawn parallel.SpawnFn) error {
> ```

can you remind me 
Does parallel return error here from the first goroutine which fails ? or how does it work?
___
*[`main.go` line 115 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHVEevFAhcQ6Rm48XRh:-NHVEevFAhcQ6Rm48XRi:b-h67996) ([raw file](https://github.com/coreumfoundation/faucet/blob/2cfdd742c535fb71c9fe09115cbb93bbe7fb2825/main.go#L115)):*
> ```Go
> 
> 	err = parallel.Run(ctx, func(ctx context.Context, spawn parallel.SpawnFn) error {
> 		batcher := coreum.NewBatcher(cl, addresses, 10)
> ```

is it actually a requirement to do all initializations inside `parallel.Run` ?
Because as for me it is logical to move it out and start parallel right before first `spawn`
___
*[`main.go` line 127 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHVF5-K92slW6U20ouK:-NHVF5-K92slW6U20ouL:b-ww1l6s) ([raw file](https://github.com/coreumfoundation/faucet/blob/2cfdd742c535fb71c9fe09115cbb93bbe7fb2825/main.go#L127)):*
> ```Go
> 		})
> 
> 		return nil
> ```

is nil always returned from parallel ?

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum)

___
*[`http/http.go` line 26 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHP31HK2YuM1LiAoPWQ:-NHVFJ1y2DCh9WKF_Ath:bb8qlsy) ([raw file](https://github.com/coreumfoundation/faucet/blob/f46133945a5f494c623852dc2e57a4acb73b668f/http/http.go#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

do we have a default value for it ? do we need one ?
because I'm afraid that Artem might forget to set it

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: all files reviewed, 4 unresolved discussions (waiting on @ysv)

___
*[`main.go` line 114 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHVEC7PA_mVqDgI4Zcp:-NHYKaDYA2I2nELLplAC:bfrmxvq) ([raw file](https://github.com/coreumfoundation/faucet/blob/2cfdd742c535fb71c9fe09115cbb93bbe7fb2825/main.go#L114)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can you remind me 
Does parallel return error here from the first goroutine which fails ? or how does it work?
</blockquote></details>

yes, first reported error is returned
___
*[`main.go` line 115 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHVEevFAhcQ6Rm48XRh:-NHYKev3-M7XzemXYmZk:b8aez8u) ([raw file](https://github.com/coreumfoundation/faucet/blob/2cfdd742c535fb71c9fe09115cbb93bbe7fb2825/main.go#L115)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it actually a requirement to do all initializations inside `parallel.Run` ?
Because as for me it is logical to move it out and start parallel right before first `spawn`
</blockquote></details>

no, it's up to the user. It's just a hint that for better readability stuff related to goroutine preparation is done inside. But space for interpretation is huge.
___
*[`main.go` line 127 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHVF5-K92slW6U20ouK:-NHYL0uhAVe8kzjea8Wf:b-8t5ki4) ([raw file](https://github.com/coreumfoundation/faucet/blob/2cfdd742c535fb71c9fe09115cbb93bbe7fb2825/main.go#L127)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is nil always returned from parallel ?
</blockquote></details>

No. If you have some code inside which errors out, error should be returned. It's like this:

```go
err := func() error {
  return errors.New(...)
}()
```
___
*[`http/http.go` line 26 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/29#-NHP31HK2YuM1LiAoPWQ:-NHYLUhF18qWDbnodsls:bwytm6p) ([raw file](https://github.com/coreumfoundation/faucet/blob/f46133945a5f494c623852dc2e57a4acb73b668f/http/http.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we have a default value for it ? do we need one ?
because I'm afraid that Artem might forget to set it
</blockquote></details>

Yes. It is set here:

```go
flagSet.StringVar(&ipRateLimit, flagIPRateLimit, "2/1h", "limit of requests per IP in the format <num-of-req>/<period>")
```

to `"2/1h"`

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
