### PR TITLE
Refactor integration tests to use default go test framework

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/31)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
