### PR TITLE
added integration test for transfer token

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/transfer_test.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBC94B-1ScdJop97USO:-NBC94B-1ScdJop97USP:bq5rp4j) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L25)):*
> ```Go
> 
> type testConfig struct {
> 	nodeURI        string
> ```

Please make the fields public as they are the "interface" of the struct
___
*[`integration-tests/transfer_test.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBC8nIgAgIKbFEZWHEm:-NBC8nIgAgIKbFEZWHEn:bqjs0ck) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L35)):*
> ```Go
> 
> func TestMain(m *testing.M) {
> 	flag.StringVar(&cfg.nodeURI, "nodeURI", "localhost:26656", "Address of cored node started by znet")
> ```

`node-uri`
___
*[`integration-tests/transfer_test.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBC8pKq9Nc1JnqrHRse:-NBC8pKq9Nc1JnqrHRsf:b-gigsz6) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L36)):*
> ```Go
> func TestMain(m *testing.M) {
> 	flag.StringVar(&cfg.nodeURI, "nodeURI", "localhost:26656", "Address of cored node started by znet")
> 	flag.StringVar(&cfg.faucetURI, "faucetURI", "http://localhost:8090", "Address of the faucet")
> ```

`faucet-uri`
___
*[`integration-tests/transfer_test.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBC9-Mm4UhuQ8Kdgm78:-NBC9-Mm4UhuQ8Kdgm79:bgcdfzv) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L37)):*
> ```Go
> 	flag.StringVar(&cfg.nodeURI, "nodeURI", "localhost:26656", "Address of cored node started by znet")
> 	flag.StringVar(&cfg.faucetURI, "faucetURI", "http://localhost:8090", "Address of the faucet")
> 	flag.StringVar(&cfg.transferAmount, "transfer-amount", "1000000", "Amount transferred by faucet in each request")
> ```

Non-blocking: this could be hardcoded IMO
___
*[`integration-tests/transfer_test.go` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBCAJfd9P-Uz3KXSv-e:-NBCAJfd9P-Uz3KXSv-f:b-s16w41) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L67)):*
> ```Go
> 
> 	// make assertions
> 	assert.EqualValues(t, cfg.transferAmount, resp.Balances.AmountOf(cfg.network.TokenSymbol()).String())
> ```

Non-blocking: For now it works only because faucet sends funds synchronously. Once faucet works asynchronously this test will fail here.
___
*[`integration-tests/transfer_test.go` line 77 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBC9ijQ9db6NAGhTjQR:-NBC9ijR5Iz3G3H2xQRO:b-rch7cx) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L77)):*
> ```Go
> 		Address: address,
> 	}
> 	payloadBuffer := bytes.NewBuffer(nil)
> ```

Minor: `&bytes.Buffer{}`
___
*[`integration-tests/transfer_test.go` line 97 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBCA6SB7zaV8plPBI_o:-NBCA6SB7zaV8plPBI_p:b-xkgi1u) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L97)):*
> ```Go
> 	defer res.Body.Close()
> 
> 	body, err := io.ReadAll(res.Body)
> ```

you use `json.NewEncoder` above, so maybe for consistency you could use `json.NewDecoder` here

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/transfer_test.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBC94B-1ScdJop97USO:-NBCjR-5EbN1FvFhN90m:b-qhjcd1) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L25)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please make the fields public as they are the "interface" of the struct
</blockquote></details>

it is used locally, so I see no benefits to make them public.
@ysv @dzmitryhil WDYT ?
___
*[`integration-tests/transfer_test.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBC8nIgAgIKbFEZWHEm:-NBCjaEJ4MekpAMguKFZ:bjij8gq) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`node-uri`
</blockquote></details>

Converted to cored-address
___
*[`integration-tests/transfer_test.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBC8pKq9Nc1JnqrHRse:-NBCjfg30Hqa5kV8Q4uR:b-v05gwf) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`faucet-uri`
</blockquote></details>

converted to faucet-address
___
*[`integration-tests/transfer_test.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBC9-Mm4UhuQ8Kdgm78:-NBCjn_b9OSLPveF71XD:b-e1td5m) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Non-blocking: this could be hardcoded IMO
</blockquote></details>

does not hurt to have this value since we might change it in the future via flags and may want to see if it takes affect correctly. 
___
*[`integration-tests/transfer_test.go` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBCAJfd9P-Uz3KXSv-e:-NBCk4VjDxD2rtAXV0RX:bxu9udi) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L67)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Non-blocking: For now it works only because faucet sends funds synchronously. Once faucet works asynchronously this test will fail here.
</blockquote></details>

faucet will always send synchronously, if it changes, we will adjust accordingley
___
*[`integration-tests/transfer_test.go` line 77 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBC9ijQ9db6NAGhTjQR:-NBCkFp28kmx6Bg5JbwV:bsvtn2i) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L77)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Minor: `&bytes.Buffer{}`
</blockquote></details>

I prefer using constructor
___
*[`integration-tests/transfer_test.go` line 97 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBCA6SB7zaV8plPBI_o:-NBCkwT27ZJTW_KhFyvN:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L97)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you use `json.NewEncoder` above, so maybe for consistency you could use `json.NewDecoder` here
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/transfer_test.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBC94B-1ScdJop97USO:-NBGP9Zr-wxTkPEejxMm:bqkeaq0) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L25)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it is used locally, so I see no benefits to make them public.
@ysv @dzmitryhil WDYT ?
</blockquote></details>

This is the convention I try to convince everyone to use. Usually object is consisted of two parts:
- interface (fields and methods) used by others
- internal stuff (fields and methods) which should not be used by others

Even if struct is used in the same package only (and is not exported), it is still convenient to export fields and methods which are the interface of the object to indicate that particular field or method should or should not be used by the caller. It's about making other developers' life easier.
___
*[`integration-tests/transfer_test.go` line 34 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBGQ4Sc6miLDrHtHRsn:-NBGQ4Sc6miLDrHtHRso:bqpwze7) ([raw file](https://github.com/coreumfoundation/faucet/blob/31cc0a86fa8e183019cff62d3c926bbebe31ca12/integration-tests/transfer_test.go#L34)):*
> ```Go
> 
> func TestMain(m *testing.M) {
> 	flag.StringVar(&cfg.coredAddress, "cored-address", "localhost:26656", "Address of cored node started by znet")
> ```

protocol is required now so `tcp://localhost:26657` (port is incorrect too)
___
*[`integration-tests/transfer_test.go` line 38 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBGQIcy9JrP3i8Lil96:-NBGQIcy9JrP3i8Lil97:bqe2xba) ([raw file](https://github.com/coreumfoundation/faucet/blob/31cc0a86fa8e183019cff62d3c926bbebe31ca12/integration-tests/transfer_test.go#L38)):*
> ```Go
> 	flag.StringVar(&cfg.transferAmount, "transfer-amount", "1000000", "Amount transferred by faucet in each request")
> 	flag.Parse()
> 	rpcClient, err := client.NewClientFromNode("tcp://" + cfg.coredAddress)
> ```

to be consistent with coreum test, let's remove protocol from here, it is defined as a part of CLI flag so it might be changed by the user

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/transfer_test.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBC94B-1ScdJop97USO:-NBGoALt9CdVRGP_3Wii:b-nfwq35) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L25)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is the convention I try to convince everyone to use. Usually object is consisted of two parts:
- interface (fields and methods) used by others
- internal stuff (fields and methods) which should not be used by others

Even if struct is used in the same package only (and is not exported), it is still convenient to export fields and methods which are the interface of the object to indicate that particular field or method should or should not be used by the caller. It's about making other developers' life easier.
</blockquote></details>

I see what you mean, and there is merit to it. 
But I tend to disagree with that convention. I think that the convention should be that fields should be exported only if they need to be visible outside the package. 
___
*[`integration-tests/transfer_test.go` line 34 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBGQ4Sc6miLDrHtHRsn:-NBGozjp4yuOyRp-CovT:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/31cc0a86fa8e183019cff62d3c926bbebe31ca12/integration-tests/transfer_test.go#L34)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

protocol is required now so `tcp://localhost:26657` (port is incorrect too)
</blockquote></details>

Done.
___
*[`integration-tests/transfer_test.go` line 38 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBGQIcy9JrP3i8Lil96:-NBGp3_0AwkRA9CNljkU:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/31cc0a86fa8e183019cff62d3c926bbebe31ca12/integration-tests/transfer_test.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

to be consistent with coreum test, let's remove protocol from here, it is defined as a part of CLI flag so it might be changed by the user
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @ysv)

___
*[`integration-tests/transfer_test.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBC94B-1ScdJop97USO:-NBHeh5h3gRxbmhl7G8m:b-ev7d7c) ([raw file](https://github.com/coreumfoundation/faucet/blob/e53d5b50003031a9d51b0aec64c8fab02d1cbd28/integration-tests/transfer_test.go#L25)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I see what you mean, and there is merit to it. 
But I tend to disagree with that convention. I think that the convention should be that fields should be exported only if they need to be visible outside the package. 
</blockquote></details>

It's enough the set the struct unxeported to protect if from being exported, if you want to do it, but that isn't required.
We can have Exported fields if we allow to set them directly without the New... functions.
And also we can keep the Methods, Functions names exported is they are primary, where the "unxported" just the function used by the Exported.

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman and @miladz68)

___
*[`integration-tests/transfer_test.go` line 20 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBHs0Z52NVRhDEj8BUy:-NBHs0Z52NVRhDEj8BUz:b6ntcqe) ([raw file](https://github.com/coreumfoundation/faucet/blob/8a12b1c251e9231b82d1b596155ecd6f01ae4697/integration-tests/transfer_test.go#L20)):*
> ```Go
> 	"github.com/CoreumFoundation/coreum-tools/pkg/must"
> 	"github.com/CoreumFoundation/coreum/app"
> 	h "github.com/CoreumFoundation/faucet/http"
> ```

`faucethttp` ?
or `nethttp "net/http"`
___
*[`integration-tests/transfer_test.go` line 50 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBHs4yZBKlzb9eFxVF2:-NBHs4yZBKlzb9eFxVF3:byer6yv) ([raw file](https://github.com/coreumfoundation/faucet/blob/8a12b1c251e9231b82d1b596155ecd6f01ae4697/integration-tests/transfer_test.go#L50)):*
> ```Go
> }
> 
> func TestTransferRequest(t *testing.T) {
> ```

is it a big hassle to add non-happy path ? 
e.g wrong address is the only one I recall

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman and @ysv)

___
*[`integration-tests/transfer_test.go` line 20 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBHs0Z52NVRhDEj8BUy:-NBLq_g5A7JKqzP6ixP0:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/8a12b1c251e9231b82d1b596155ecd6f01ae4697/integration-tests/transfer_test.go#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`faucethttp` ?
or `nethttp "net/http"`
</blockquote></details>

Done.
___
*[`integration-tests/transfer_test.go` line 50 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBHs4yZBKlzb9eFxVF2:-NBLtv697O6yROIZulph:b-redcrj) ([raw file](https://github.com/coreumfoundation/faucet/blob/8a12b1c251e9231b82d1b596155ecd6f01ae4697/integration-tests/transfer_test.go#L50)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it a big hassle to add non-happy path ? 
e.g wrong address is the only one I recall 
</blockquote></details>

Added test for wrong address

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

___
*[`integration-tests/transfer_test.go` line 20 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBHs0Z52NVRhDEj8BUy:-NBMTh4a5fUq5gfVXzMk:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/8a12b1c251e9231b82d1b596155ecd6f01ae4697/integration-tests/transfer_test.go#L20)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok
___
*[`integration-tests/transfer_test.go` line 50 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBHs4yZBKlzb9eFxVF2:-NBMTdp26F7piFb_sxBg:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/8a12b1c251e9231b82d1b596155ecd6f01ae4697/integration-tests/transfer_test.go#L50)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Added test for wrong address
</blockquote></details>

ok

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @miladz68)

___
*[`integration-tests/transfer_test.go` line 71 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBMVUB49wsEZPSrzCZG:-NBMVUB49wsEZPSrzCZH:bbj0zwu) ([raw file](https://github.com/coreumfoundation/faucet/blob/c0440d4dad9ef82ddcd5903fd0e135936ce02e2d/integration-tests/transfer_test.go#L71)):*
> ```Go
> }
> 
> func TestTransferRequest_WrongAddress(t *testing.T) {
> ```

I'm not sure if it deserves an integration test. Seems like unit test inside faucet for this should be good enough

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman and @miladz68)

___
*[`integration-tests/transfer_test.go` line 116 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBMVpvW8tQlP7_yJvJG:-NBMVpvW8tQlP7_yJvJH:bfzrq0r) ([raw file](https://github.com/coreumfoundation/faucet/blob/c0440d4dad9ef82ddcd5903fd0e135936ce02e2d/integration-tests/transfer_test.go#L116)):*
> ```Go
> 		return "", err
> 	}
> 	if res.StatusCode > 299 {
> ```

How faucet responds to the request?
If it responds with emty body then it should always return `http.StatusNoContent`. Otherwise `http.StatusOK`. So you know here exactly what code is expected.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman and @miladz68)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @wojtek-coreum, and @ysv)

___
*[`integration-tests/transfer_test.go` line 71 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBMVUB49wsEZPSrzCZG:-NBMWM8z3aFQgGXceuAU:b7e9os2) ([raw file](https://github.com/coreumfoundation/faucet/blob/c0440d4dad9ef82ddcd5903fd0e135936ce02e2d/integration-tests/transfer_test.go#L71)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I'm not sure if it deserves an integration test. Seems like unit test inside faucet for this should be good enough
</blockquote></details>

@ysv comments ?
___
*[`integration-tests/transfer_test.go` line 116 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBMVpvW8tQlP7_yJvJG:-NBMWSk9EHReZbvPnqlh:b-x23hfm) ([raw file](https://github.com/coreumfoundation/faucet/blob/c0440d4dad9ef82ddcd5903fd0e135936ce02e2d/integration-tests/transfer_test.go#L116)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

How faucet responds to the request?
If it responds with emty body then it should always return `http.StatusNoContent`. Otherwise `http.StatusOK`. So you know here exactly what code is expected.
</blockquote></details>

well it depends, it might have different errors based on the nature of the error. like wrong address is it will give 406 Not Acceptable error. for the purposes of this test, the fact that error is returned in good enough IMO.

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman and @wojtek-coreum)

___
*[`integration-tests/transfer_test.go` line 71 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBMVUB49wsEZPSrzCZG:-NBMZIPfBuGl0SBpTv6j:b-mft50l) ([raw file](https://github.com/coreumfoundation/faucet/blob/c0440d4dad9ef82ddcd5903fd0e135936ce02e2d/integration-tests/transfer_test.go#L71)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@ysv comments ?
</blockquote></details>

I asked about it 
For me it makes sense lets keep it
___
*[`integration-tests/transfer_test.go` line 116 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBMVpvW8tQlP7_yJvJG:-NBMZRbq65LW-o8ti-VE:bc0dpj) ([raw file](https://github.com/coreumfoundation/faucet/blob/c0440d4dad9ef82ddcd5903fd0e135936ce02e2d/integration-tests/transfer_test.go#L116)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

well it depends, it might have different errors based on the nature of the error. like wrong address is it will give 406 Not Acceptable error. for the purposes of this test, the fact that error is returned in good enough IMO.  
</blockquote></details>

`statusCode > 299` is ok for me

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman and @wojtek-coreum)

___
*[`integration-tests/transfer_test.go` line 71 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBMVUB49wsEZPSrzCZG:-NBM_7Qc4BM56lL9ZROR:bt6n0et) ([raw file](https://github.com/coreumfoundation/faucet/blob/c0440d4dad9ef82ddcd5903fd0e135936ce02e2d/integration-tests/transfer_test.go#L71)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I asked about it 
For me it makes sense lets keep it
</blockquote></details>

what we have in unit tests is just parse_address test 
I don't insist on testing all possible non-happy scenarios but since this one is simple to check and very common I think it is fine

By the way what I would prefer to test here is wrong network address instead eg. testcore instead of devcore

I think it is going to be super common

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`integration-tests/transfer_test.go` line 71 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBMVUB49wsEZPSrzCZG:-NBMehKcEOB-ExhgC7_6:bc9bu5l) ([raw file](https://github.com/coreumfoundation/faucet/blob/c0440d4dad9ef82ddcd5903fd0e135936ce02e2d/integration-tests/transfer_test.go#L71)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what we have in unit tests is just parse_address test 
I don't insist on testing all possible non-happy scenarios but since this one is simple to check and very common I think it is fine

By the way what I would prefer to test here is wrong network address instead eg. testcore instead of devcore

I think it is going to be super common 

</blockquote></details>

As @ysv said, I agree that it is better to take **valid** adress from different network and check

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @wojtek-coreum)

___
*[`integration-tests/transfer_test.go` line 71 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/9#-NBMVUB49wsEZPSrzCZG:-NBMr1MDBoCKlQxElfc_:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/c0440d4dad9ef82ddcd5903fd0e135936ce02e2d/integration-tests/transfer_test.go#L71)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

As @ysv said, I agree that it is better to take **valid** adress from different network and check
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

**Pull request merged**
