### PR TITLE
fix test failure when queries go to different nodes

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/21)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/21)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/transfer_test.go` line 76 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/21#-NCsCNsUCxFy04R-VkNH:-NCsCNsUCxFy04R-VkNI:b-8vwmkk) ([raw file](https://github.com/coreumfoundation/faucet/blob/53b7ea5a7f671587db83df1cacbae05a7bd155f1/integration-tests/transfer_test.go#L76)):*
> ```Go
> 	require.Len(t, txHash, 64)
> 
> 	// wait for one block, so all nodes are synced
> ```

please briefly explain the issue it's solving

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/21)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/21)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/transfer_test.go` line 76 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/21#-NCsCNsUCxFy04R-VkNH:-ND1bJ2B8SejKAGEiUvo:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/53b7ea5a7f671587db83df1cacbae05a7bd155f1/integration-tests/transfer_test.go#L76)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please briefly explain the issue it's solving
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/21)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`integration-tests/transfer_test.go` line 78 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/21#-ND245Eb59l9ow8TXzb4:-ND245Eb59l9ow8TXzb5:bduiuey) ([raw file](https://github.com/coreumfoundation/faucet/blob/20f62b37bd4e8bcf727887b7cfa90ba564045f1d/integration-tests/transfer_test.go#L78)):*
> ```Go
> 
> 	// wait for one block, so all nodes are synced
> 	// it is possible and the transfer and query requests go to different nodes and although
> ```

possible and the -> possible that the

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/21)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @wojtek-coreum, and @ysv)

___
*[`integration-tests/transfer_test.go` line 78 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/21#-ND245Eb59l9ow8TXzb4:-ND24iQNAo2ow29rqTrV:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/20f62b37bd4e8bcf727887b7cfa90ba564045f1d/integration-tests/transfer_test.go#L78)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

possible and the -> possible that the
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @ysv)

**Pull request merged**
