### PR TITLE
Use `X-Original-Forwarded-For` header to determine source IP address

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/49)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/49)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`pkg/http/middleware.go` line 57 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/49#-NOLFD8o-NVDzDn-zaNv:-NOLFD8p2jpxcFuE9d1B:ba7xmlz) ([raw file](https://github.com/CoreumFoundation/faucet/blob/a253943abc84d1c6f2f8ac6aed637665caa8facd/pkg/http/middleware.go#L57)):*
> ```Go
> 	}
> 
> 	xForwardedFor := r.Header["X-Original-Forwarded-For"]
> ```

so if this one is empty you fall back to `echo.HeaderXForwardedFor` ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/49)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/http/middleware.go` line 57 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/49#-NOLFD8o-NVDzDn-zaNv:-NOO2V-SEyrJMcth5gQD:b2nign3) ([raw file](https://github.com/CoreumFoundation/faucet/blob/a253943abc84d1c6f2f8ac6aed637665caa8facd/pkg/http/middleware.go#L57)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so if this one is empty you fall back to `echo.HeaderXForwardedFor` ?
</blockquote></details>

yep

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/49)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/49)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/49)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Pull request merged**
