### PR TITLE
Add CI workflow

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/2)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/2)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`.github/workflows/ci.yml` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/2#-NADeIZV8jgIusPVgIaw:-NADeIZV8jgIusPVgIax:bgvlc02) ([raw file](https://github.com/coreumfoundation/faucet/blob/d50c0434fedb5a87dcb1d9b5ad97538097bfd1bc/.github/workflows/ci.yml#L26)):*
> ```YAML
>         run: crust lint test build --log-format=yaml
>       - name: Execute integration tests
>         run: crust znet test --log-format=yaml
> ```

I don't think we need to run znet test here in this repo.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/2)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`.github/workflows/ci.yml` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/2#-NADeIZV8jgIusPVgIaw:-NAE4GbcEUIDVr-lida8:bf6o5ji) ([raw file](https://github.com/coreumfoundation/faucet/blob/d50c0434fedb5a87dcb1d9b5ad97538097bfd1bc/.github/workflows/ci.yml#L26)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think we need to run znet test here in this repo. 
</blockquote></details>

Aren't we going to add an integration test here which checks that after sending a request funds are transferred to the provided address?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/2)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, and @xlab)

___
*[`.github/workflows/ci.yml` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/2#-NADeIZV8jgIusPVgIaw:-NAEPz4j1DwG8IyBu1u_:bcg2pbs) ([raw file](https://github.com/coreumfoundation/faucet/blob/d50c0434fedb5a87dcb1d9b5ad97538097bfd1bc/.github/workflows/ci.yml#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Aren't we going to add an integration test here which checks that after sending a request funds are transferred to the provided address?
</blockquote></details>

right now we don't need but for integration tests we will probably add it

I would probably not add it right now but once we need it

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/2)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @oliverasistemas)

___
*[`.github/workflows/ci.yml` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/2#-NADeIZV8jgIusPVgIaw:-NAESun_3FbF5UjP0mNq:b7ec0ci) ([raw file](https://github.com/coreumfoundation/faucet/blob/d50c0434fedb5a87dcb1d9b5ad97538097bfd1bc/.github/workflows/ci.yml#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

right now we don't need but for integration tests we will probably add it

I would probably not add it right now but once we need it
</blockquote></details>

technically speaking we decided that new feature should go with integration test in the same PR, so the faucet PR should include it

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/2)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @oliverasistemas)

___
*[`.github/workflows/ci.yml` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/2#-NADeIZV8jgIusPVgIaw:-NAETJYw6VZiPUmJh0h2:bb53i0g) ([raw file](https://github.com/coreumfoundation/faucet/blob/d50c0434fedb5a87dcb1d9b5ad97538097bfd1bc/.github/workflows/ci.yml#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

technically speaking we decided that new feature should go with integration test in the same PR, so the faucet PR should include it
</blockquote></details>

but now I see that it's not possible because crust must deploy it first

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @oliverasistemas)

___
*[`.github/workflows/ci.yml` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/2#-NADeIZV8jgIusPVgIaw:-NAETsmq18XdcZK1df_G:baj3ezc) ([raw file](https://github.com/coreumfoundation/faucet/blob/d50c0434fedb5a87dcb1d9b5ad97538097bfd1bc/.github/workflows/ci.yml#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but now I see that it's not possible because crust must deploy it first
</blockquote></details>

Commented for now

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @oliverasistemas)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @dzmitryhil, and @oliverasistemas)

**Pull request merged**
