### PR TITLE
Report balances of faucet accounts

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/72)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/72)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @bashash, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`main.go` line 231 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/72#-N_DywQuB-zVDxpCOZZt:-N_DywQuB-zVDxpCOZZu:bb9i15q) ([raw file](https://github.com/CoreumFoundation/faucet/blob/d89472e2ce18c83272fb101f56cdc7fa91750c55/main.go#L231)):*
> ```Go
> 	flagSet.StringVar(&conf.node, flagNode, "localhost:9090", "<host>:<port> to Tendermint GRPC endpoint for this chain")
> 	flagSet.StringVar(&conf.address, flagAddress, ":8090", "<host>:<port> address to start listening for http requests")
> 	flagSet.StringVar(&conf.monitoringAddress, flagMonitoringAddress, ":9090", "<host>:<port> address to expose metrics to")
> ```

I propose to choose a port, by default, which we don't use to be able to run the faucet and node on the same machine without the reconfiguration at the same time.
___
*[`app/monitoring.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/72#-N_E-JPMBcsfHT9IqKMq:-N_E-JPMBcsfHT9IqKMr:b3nmgxt) ([raw file](https://github.com/CoreumFoundation/faucet/blob/d89472e2ce18c83272fb101f56cdc7fa91750c55/app/monitoring.go#L58)):*
> ```Go
> 			log := logger.Get(ctx)
> 			bankClient := banktypes.NewQueryClient(clientCtx)
> 			for {
> ```

Why don't you use the retry here?
___
*[`app/monitoring.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/72#-N_E-JmO1NKfvluGcpmu:-N_E-JmO1NKfvluGcpmv:bur3yz7) ([raw file](https://github.com/CoreumFoundation/faucet/blob/d89472e2ce18c83272fb101f56cdc7fa91750c55/app/monitoring.go#L74)):*
> ```Go
> 				case <-ctx.Done():
> 					return errors.WithStack(ctx.Err())
> 				case <-time.After(time.Minute):
> ```

It would be nice to move the retry timeout to config. But that's optional, because of the current faucet design.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/72)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @bashash, @dzmitryhil, @miladz68, and @silverspase)

___
*[`main.go` line 231 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/72#-N_DywQuB-zVDxpCOZZt:-N_E0qYr9kXnlf0wPWAb:b-896fix) ([raw file](https://github.com/CoreumFoundation/faucet/blob/d89472e2ce18c83272fb101f56cdc7fa91750c55/main.go#L231)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I propose to choose a port, by default, which we don't use to be able to run the faucet and node on the same machine without the reconfiguration at the same time.
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/72)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @bashash, @miladz68, and @silverspase)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/72)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash, @miladz68, and @silverspase)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/72)* status: all files reviewed, 1 unresolved discussion (waiting on @bashash, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`app/monitoring.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/72#-N_E-JPMBcsfHT9IqKMq:-N_E1eZO5y2M2yqMmo1t:b-xw7it1) ([raw file](https://github.com/CoreumFoundation/faucet/blob/d89472e2ce18c83272fb101f56cdc7fa91750c55/app/monitoring.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But that's in general the design of it. We do the retry when we need the retry, and the error is just a hint for it. 
</blockquote></details>

I mean I don't see a big difference, but the usage of retry lets you use less code.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/72)* status: all files reviewed, 1 unresolved discussion (waiting on @bashash, @dzmitryhil, @miladz68, and @silverspase)

___
*[`app/monitoring.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/72#-N_E-JPMBcsfHT9IqKMq:-N_E8C1J34JqpzVHBKXP:b-kmw2oz) ([raw file](https://github.com/CoreumFoundation/faucet/blob/d89472e2ce18c83272fb101f56cdc7fa91750c55/app/monitoring.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I mean I don't see a big difference, but the usage of retry lets you use less code.
</blockquote></details>

producing an error when everything is fine is not a good idea IMO

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/72)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash and @silverspase)

**Pull request merged**
