### PR TITLE
Integrate grpc client

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/46)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/46)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`main.go` line 107 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/46#-NNqOIfG6xD_o1iLSsOU:-NNqOIfG6xD_o1iLSsOV:b-c1yamz) ([raw file](https://github.com/CoreumFoundation/faucet/blob/d3ec9829a7ddda61b9249a5f63cd0e4ce1fa7572/main.go#L107)):*
> ```Go
> 		clientCtx = clientCtx.WithRPCClient(rpcClient)
> 	} else {
> 		grpcClient, err := grpc.Dial(cfg.node, grpc.WithTransportCredentials(insecure.NewCredentials()))
> ```

Locally for znet we need insecure, but for public faucet we need TLS 
___
*[`integration-tests/transfer_test.go` line 97 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/46#-NNqOze0ALy_LZIMlGsJ:-NNqOze0ALy_LZIMlGsK:b-49hn1g) ([raw file](https://github.com/CoreumFoundation/faucet/blob/952431c7584aed32d8787329b0cd3c358b5636bd/integration-tests/transfer_test.go#L97)):*
> ```Go
> // and does not have the transaction included in a block and its state will be different.
> // By waiting for one block we make sure that all nodes are synced on the previous block.
> func waitForTxInclusionAndSync(ctx context.Context, clientCtx coreumtx.ClientContext, txHash string) error {
> ```

why is it removed? I think the problem still exists, no?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/46)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`main.go` line 107 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/46#-NNqOIfG6xD_o1iLSsOU:-NNqS9IA0xfXy5u5r8mG:bdktmld) ([raw file](https://github.com/CoreumFoundation/faucet/blob/d3ec9829a7ddda61b9249a5f63cd0e4ce1fa7572/main.go#L107)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Then we need to define how to set it, we can use "https://" prefix to enable the `TLS` and if not the `https` then `insecure`, but the issue that that GRPC is not http :-)  
</blockquote></details>

let's use grpc:// and grpcs:// :D
___
*[`integration-tests/transfer_test.go` line 97 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/46#-NNqOze0ALy_LZIMlGsJ:-NNqSF2k9eP6h9uF7UzZ:b-tu2ghw) ([raw file](https://github.com/CoreumFoundation/faucet/blob/952431c7584aed32d8787329b0cd3c358b5636bd/integration-tests/transfer_test.go#L97)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't see the issue, we do the same in the coreum integration tests, and all if fine there. 
</blockquote></details>

I think @miladz68 introduced it because errors appeared randomly

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/46)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`main.go` line 167 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/46#-NNunYOQEM1OlZnJb5QE:-NNunYOQEM1OlZnJb5QF:b-5xysi2) ([raw file](https://github.com/CoreumFoundation/faucet/blob/26d4d398b65d0b91a1e6e2d9bcac3516eca11248/main.go#L167)):*
> ```Go
> 	// no-tls grpc
> 	host := nodeURL.Host
> 	// this situation is possible the protocol wasn't provided, in such senanario we use the
> ```

if the protocol wasn't provided
senanario
we use... what?
___
*[`main.go` line 167 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/46#-NNunmiV1ZFsL6gR8Ahf:-NNunmiV1ZFsL6gR8Ahg:bx8andy) ([raw file](https://github.com/CoreumFoundation/faucet/blob/26d4d398b65d0b91a1e6e2d9bcac3516eca11248/main.go#L167)):*
> ```Go
> 	// no-tls grpc
> 	host := nodeURL.Host
> 	// this situation is possible the protocol wasn't provided, in such senanario we use the
> ```

I don't get it, if protocol hasn't been provided then `Scheme` should be empty, not `Host`

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/46)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`main.go` line 167 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/46#-NNunmiV1ZFsL6gR8Ahf:-NNv3tSeAe46a5mKQ92m:bbj4r18) ([raw file](https://github.com/CoreumFoundation/faucet/blob/26d4d398b65d0b91a1e6e2d9bcac3516eca11248/main.go#L167)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually not, in that case the Schema will be filled, and host is empty :-) That's the URL implementation
</blockquote></details>

you mean that if I provide `host.com` instead of `http://host.com`, then Schema is `host.com` and host is empty?
___
*[`main.go` line 167 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/46#-NNunYOQEM1OlZnJb5QE:-NNv45Hi1SLcCPEPVI3K:b-eakn75) ([raw file](https://github.com/CoreumFoundation/faucet/blob/26d4d398b65d0b91a1e6e2d9bcac3516eca11248/main.go#L167)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We use the grpc without the TLS
</blockquote></details>

yea, so please fix the comment

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/46)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/46)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/46)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
