### PR TITLE
Use SDK config to generate HD paths & update coreum dependency

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/25)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @dzmitryhil, and @miladz68)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/25)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/send_with_privkey.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/25#-NDXg1pfDQKAPLoi6bSO:-NDXg1pg0jWt0d7u1MlP:b-f8led6) ([raw file](https://github.com/coreumfoundation/faucet/blob/c500d7b2558ec9ea89e7af22447a4a6ea4fe0f03/app/send_with_privkey.go#L13)):*
> ```Go
> 
> var (
> 	hdPath = sdk.GetConfig().GetFullBIP44Path()
> ```

You don't need this var, just call the method as you did in the main.
___
*[`app/send_with_privkey.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/25#-NDXfFraA5IalBwCuUrg:-NDXfFraA5IalBwCuUrh:bosju2l) ([raw file](https://github.com/coreumfoundation/faucet/blob/c500d7b2558ec9ea89e7af22447a4a6ea4fe0f03/app/send_with_privkey.go#L24)):*
> ```Go
> 
> // GenPrivkeyAndFund generates a private key and funds it
> func (a App) GenPrivkeyAndFund(ctx context.Context) (GenPrivKeyAndFundResponse, error) {
> ```

The method name isn't correct anymore, and the struct name, since you generate the mnemonic, not the private key. And file name as well :-)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/25)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/25)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`app/send_with_privkey.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/25#-NDXg1pfDQKAPLoi6bSO:-NDXioZ80GVaO5DV9eX3:bb7f2mf) ([raw file](https://github.com/coreumfoundation/faucet/blob/c500d7b2558ec9ea89e7af22447a4a6ea4fe0f03/app/send_with_privkey.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You don't need this var, just call the method as you did in the main.
</blockquote></details>

done
___
*[`app/send_with_privkey.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/25#-NDXfFraA5IalBwCuUrg:-NDXihlp7yZNJvf8WyQF:b-lrvwse) ([raw file](https://github.com/coreumfoundation/faucet/blob/c500d7b2558ec9ea89e7af22447a4a6ea4fe0f03/app/send_with_privkey.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The method name isn't correct anymore, and the struct name, since you generate the mnemonic, not the private key. And file name as well :-)
</blockquote></details>

renamed all

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/25)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

**Pull request merged**
