### PR TITLE
Run integration tests in CI

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/7)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/7)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/7#-NAn1tE2DM_7DNayYLMI:-NAn1tE2DM_7DNayYLMJ:b-jwb0cr) (no related file):*
let's not enable tests before we have faucet specific integration tests.

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/7)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/7#-NAn1tE2DM_7DNayYLMI:-NAn7JrKDqRo4PX-j1uO:bpxvmdn) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's not enable tests before we have faucet specific integration tests.
</blockquote></details>

The fact is that changes in faucet might break the CI environment. E.g. if `/status` is accidentally removed or broken the `znet` won't work correctly meaning that all the PRs in other repos start failing. That was the case yesterday when @ysv reverted `master` to some old version. BTW, no matter what please don't do this anymore - such updates don't come through CI and everything might be broken. 

___

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/7)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/7#-NAn1tE2DM_7DNayYLMI:-NAstDRZ3bLrharwKEW1:b-lquo1g) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The fact is that changes in faucet might break the CI environment. E.g. if `/status` is accidentally removed or broken the `znet` won't work correctly meaning that all the PRs in other repos start failing. That was the case yesterday when @ysv reverted `master` to some old version. BTW, no matter what please don't do this anymore - such updates don't come through CI and everything might be broken. 
</blockquote></details>

It was force-pushed intentionaly to have clean git history without merge commits
And after this I put protection for master branch and enforced other rules

Not critical for me to merge it now or after integration tests are done
If it causes inconvenience for Milad we can wait if ok lets merge

___

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/7)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/7#-NAn1tE2DM_7DNayYLMI:-NAswsTi4x3UDQwsX7Rx:b-q5b57e) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

It was force-pushed intentionaly to have clean git history without merge commits
And after this I put protection for master branch and enforced other rules

Not critical for me to merge it now or after integration tests are done
If it causes inconvenience for Milad we can wait if ok lets merge
</blockquote></details>

I would say that it is logical to enable these test on the same PR where we introduce them

___

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/7)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/7#-NAn1tE2DM_7DNayYLMI:-NAt2IJH3fVcv3VpEEbz:b-p235p9) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would say that it is logical to enable these test on the same PR where we introduce them
</blockquote></details>

it is not in anyway an inconveniece, but those tests test coreum repo, running them here is meaningless. 

___

**Pull request closed without merging**
