### PR TITLE
Fix parsing of X-Forwarded-For header

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/32)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Review by ysv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Review by miladz68 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/32#-:-NJkK-wP0P4TN8HiUhEl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
