### PR TITLE
Build and push docker image with git tag

### PR DESCRIPTION
**Pull request by vertex451**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/48)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/48)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/faucet/48#-NO9x54o6V3mGD4B5OR0:-NO9x54o6V3mGD4B5OR1:b-8cjizp) (no related file):*
Please give a better title to the PR

___
___
*[`.github/workflows/ci.yml` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/48#-NO9x7hqEykt6qlHLnUS:-NO9x7hqEykt6qlHLnUT:b-ekr2qm) ([raw file](https://github.com/CoreumFoundation/faucet/blob/372726cd8f910cbb967abcfd4602bfd568e3210f/.github/workflows/ci.yml#L1)):*
> ```YAML
> #name: ci
> ```

everything is commented. leftover?

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/48)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 77 at r3](https://reviewable.io/reviews/CoreumFoundation/faucet/48#-NOIz5zjE9bn3iHE8J1N:-NOIz5zkCudNuGiqORwP:b-8wlz3l) ([raw file](https://github.com/CoreumFoundation/faucet/blob/0c9efcbad1f21c17a943b6f0b1752a5f50b68c22/.github/workflows/ci.yml#L77)):*
> ```YAML
>       - name: Dump docker logs on failure
>         if: failure()
>         uses: jwalton/gh-docker-logs@v2
> ```

needs empty line at the end of file. :D

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/48)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`.github/workflows/release.yml` line 5 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/48#-NOJ0m1r6u6710OLUzA8:-NOJ0m1r6u6710OLUzA9:b-pjq19h) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c9efcbad1f21c17a943b6f0b1752a5f50b68c22/.github/workflows/release.yml#L5)):*
> ```YAML
>   push:
>     tags:
>       - "v[0-9]+.[0-9]+.[0-9]+*"
> ```

by removing this new release will be created on every push to master. If we want to build docker image every time, then separate file should be created instead.
___
*[`.github/workflows/release.yml` line 16 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/48#-NOJ0xxX12vbmeGpPJqM:-NOJ0xxX12vbmeGpPJqN:b-h6nbpo) ([raw file](https://github.com/coreumfoundation/faucet/blob/dbdf7c9c896ae77579f6e8e80dacd805e020b6ed/.github/workflows/release.yml#L16)):*
> ```YAML
>     steps:
>       - name: Checkout
>         uses: actions/checkout@v2
> ```

let's use v3

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/48)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`.github/workflows/release.yml` line 5 at r3](https://reviewable.io/reviews/CoreumFoundation/faucet/48#-NOJ0m1r6u6710OLUzA8:-NOJVd0yBV8h-oFAW-KE:b7fz86g) ([raw file](https://github.com/CoreumFoundation/faucet/blob/0c9efcbad1f21c17a943b6f0b1752a5f50b68c22/.github/workflows/release.yml#L5)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

No, there is a check if defines is it a release tag or pre-release tag, if nothing of above, release is skipped
</blockquote></details>

I see it now. But anyway, wouldn't it be easier to maintain if those things are separated anyway? @ysv WDYT?

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/48)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/48)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`.github/workflows/release.yml` line 5 at r3](https://reviewable.io/reviews/CoreumFoundation/faucet/48#-NOJ0m1r6u6710OLUzA8:-NOK8Ks81M39PhF_Hr1z:b79004t) ([raw file](https://github.com/CoreumFoundation/faucet/blob/0c9efcbad1f21c17a943b6f0b1752a5f50b68c22/.github/workflows/release.yml#L5)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I see it now. But anyway, wouldn't it be easier to maintain if those things are separated anyway? @ysv WDYT?
</blockquote></details>

I tend to agree with Wojtek's approach
lets split into multiple files

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/48)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`.github/workflows/release.yml` line 7 at r7](https://reviewable.io/reviews/CoreumFoundation/faucet/48#-NOOboeU2Hs8ziBYeXH1:-NOOboeU2Hs8ziBYeXH2:b1np0fk) ([raw file](https://github.com/CoreumFoundation/faucet/blob/ff91fb22f2aaf7f20b1fa99ada59f6967903d985/.github/workflows/release.yml#L7)):*
> ```YAML
>       - 'master'
> 
> env:
> ```

Is it needed now?
___
*[`.github/workflows/release.yml` line 15 at r7](https://reviewable.io/reviews/CoreumFoundation/faucet/48#-NOObti_03HQuLg1nIUa:-NOObti_03HQuLg1nIUb:b1np0fk) ([raw file](https://github.com/CoreumFoundation/faucet/blob/ff91fb22f2aaf7f20b1fa99ada59f6967903d985/.github/workflows/release.yml#L15)):*
> ```YAML
>     runs-on: ubuntu-22.04
>     steps:
>       - name: Checkout
> ```

Is it needed now?

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/48)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Pull request merged**
