### PR TITLE
Disable Parallel in transfer integration tests.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/39)

### CODE REVIEW

**Review by miladz68 — COMMENTED** [review]
Why do we need this ?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/39#-:-NLMLoOd9cPFgIZv56EK:be8a1e5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
That's the only difference in the tests before and after the direct usage of the unit tests framework. Now in 50% cases on the CI the tests don't pass. So that's just a check to understand that that's the issue :-)

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/39#-:-NLPNyuZ-7Vz9tLQojKC:bk5rkej)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/39)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/39)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — APPROVED** [review]
I'm ok to try
What about testing this locally does it seems to work ?

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/39#-:-NLQTXj-0uFos-HGrxEI:btxmen)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request closed without merging**
