### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by wojtek-coreum**
- upgrade `coreum`
- add logging
- add `/status` endpoint so `znet` may know that faucet is ready to serve requests
- fix bug with wrong decoding sender's private key to bech32 address
- change `send-money` request to `POST` because it's more natural for operations which update state

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/4)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/4)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, and @wojtek-coreum)

___
*[`http/http.go` line 39 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/4#-NAcjpOj72TI1NZJtk9Y:-NAcjpOj72TI1NZJtk9Z:b-3kbmxd) ([raw file](https://github.com/coreumfoundation/faucet/blob/1a039b526100855fe1634bc13a0abbe18b2e5afe/http/http.go#L39)):*
> ```Go
> }
> 
> // StatusResponse is the output to GiveFunds request
> ```

fix comment
___
*[`http/http.go` line 40 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/4#-NAckQJv9rGuOP-5rHvY:-NAckQJv9rGuOP-5rHvZ:b-63uttc) ([raw file](https://github.com/coreumfoundation/faucet/blob/1a039b526100855fe1634bc13a0abbe18b2e5afe/http/http.go#L40)):*
> ```Go
> 
> // StatusResponse is the output to GiveFunds request
> type StatusResponse struct {
> ```

I was always using this format:
```
struct {
  Version string `json:"version"`
  Go      string `json:"go"`
  }
```
I suggest to combine both your and mine and have version, go & status
___
*[`http/http.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/4#-NAckI1X1CBYhwsJLOur:-NAckI1X1CBYhwsJLOus:b42ij06) ([raw file](https://github.com/coreumfoundation/faucet/blob/1a039b526100855fe1634bc13a0abbe18b2e5afe/http/http.go#L47)):*
> ```Go
> func (h HTTP) statusHandle(ctx http.Context) error {
> 	return ctx.JSON(200, StatusResponse{
> 		Version: "v1",
> ```

version should be in semver format (0.1.0 , 1.1.1 etc)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/4)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`http/http.go` line 39 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/4#-NAcjpOj72TI1NZJtk9Y:-NAdBOv-1Cy-dvqzxlmK:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/1a039b526100855fe1634bc13a0abbe18b2e5afe/http/http.go#L39)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

fix comment
</blockquote></details>

Done.
___
*[`http/http.go` line 40 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/4#-NAckQJv9rGuOP-5rHvY:-NAdC41kCuQXEDRSr8a7:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/1a039b526100855fe1634bc13a0abbe18b2e5afe/http/http.go#L40)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I was always using this format:
```
struct {
  Version string `json:"version"`
  Go      string `json:"go"`
  }
```
I suggest to combine both your and mine and have version, go & status


</blockquote></details>

Done.
___
*[`http/http.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/4#-NAckI1X1CBYhwsJLOur:-NAdC69MAPARAGrf6tmF:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/1a039b526100855fe1634bc13a0abbe18b2e5afe/http/http.go#L47)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

version should be in semver format (0.1.0 , 1.1.1 etc)
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @oliverasistemas)

**Pull request merged**
