### PR TITLE
Added instructions to README

### PR DESCRIPTION
**Pull request by alinetskyi**
- Add documentation to README

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/13)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/13)* status: all files reviewed, 4 unresolved discussions (waiting on @alinetskyi, @miladz68, and @ysv)

___
*[`README.md` line 5 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/13#-NBrCpkQ0HvVFGYXl0Cv:-NBrCpkRETcCqvvtvM0o:b-xavx48) ([raw file](https://github.com/coreumfoundation/faucet/blob/25f7d58098bf58081f98f3720e21c27c99d96110/README.md#L5)):*
> ```Markdown
> ## Prerequisites
> To use `faucet` you need:
> - `go 1.17` or newer
> ```

go 1.19
___
*[`README.md` line 6 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/13#-NBrD0NZ4b1w8ETrXmQH:-NBrD0NZ4b1w8ETrXmQI:bv2bax2) ([raw file](https://github.com/coreumfoundation/faucet/blob/25f7d58098bf58081f98f3720e21c27c99d96110/README.md#L6)):*
> ```Markdown
> To use `faucet` you need:
> - `go 1.17` or newer
> - `tmux`
> ```

It's not needed
___
*[`README.md` line 58 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/13#-NBrDA610UJb2b7d9230:-NBrDA610UJb2b7d9231:b3kre) ([raw file](https://github.com/coreumfoundation/faucet/blob/25f7d58098bf58081f98f3720e21c27c99d96110/README.md#L58)):*
> ```Markdown
> ### `send_money`
> 
> Returns XRP and SOLO balance of an address.
> ```

?
___
*[`.github/workflows/ci.yml` line 1 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/13#-NBrDLyT227ORq8UIxId:-NBrDLyT227ORq8UIxIe:b-jtmve7) ([raw file](https://github.com/coreumfoundation/faucet/blob/25f7d58098bf58081f98f3720e21c27c99d96110/.github/workflows/ci.yml#L1)):*
> ```YAML
> name: ci
> ```

Image should not be published on every pull request, only when it goes to master

**Comment by alinetskyi** [comment]
*[`.github/workflows/ci.yml` line 1 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/13#-NBrDLyT227ORq8UIxId:-NBrGBld-X4y20V1Vkky:b-9zcz7c) ([raw file](https://github.com/coreumfoundation/faucet/blob/25f7d58098bf58081f98f3720e21c27c99d96110/.github/workflows/ci.yml#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Image should not be published on every pull request, only when it goes to master
</blockquote></details>

it's only name of the workflow, it's actually triggered only during master push

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/13)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`README.md` line 5 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/13#-NBrCpkQ0HvVFGYXl0Cv:-NBrGZXrBK7lcI-T1Cc6:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/25f7d58098bf58081f98f3720e21c27c99d96110/README.md#L5)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

go 1.19
</blockquote></details>

Done.
___
*[`README.md` line 6 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/13#-NBrD0NZ4b1w8ETrXmQH:-NBrG_Oj7QPtuzyWg-7I:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/25f7d58098bf58081f98f3720e21c27c99d96110/README.md#L6)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's not needed
</blockquote></details>

Done.
___
*[`README.md` line 58 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/13#-NBrDA610UJb2b7d9230:-NBrGaij9EvHLsMVOTJo:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/25f7d58098bf58081f98f3720e21c27c99d96110/README.md#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/13)* status: all files reviewed, 1 unresolved discussion (waiting on @alinetskyi, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 1 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/13#-NBrDLyT227ORq8UIxId:-NBuavBbBos7yj6kZWdH:bt5bvwe) ([raw file](https://github.com/coreumfoundation/faucet/blob/25f7d58098bf58081f98f3720e21c27c99d96110/.github/workflows/ci.yml#L1)):*
<details><summary><i>Previously, alinetskyi (Artem Linetskiy) wrote…</i></summary><blockquote>

it's only name of the workflow, it's actually triggered only during master push
</blockquote></details>

nope, check this:

```
  pull_request:
    branches: [ master ]
```

It runs whenever someone opens a pull request targetting master.
It means that everyone may fork our repo, modify source code to do some hacky stuff, open a PR and brand new hacked docker image will be published in our official repo. I guess that if you check the docker repo you will find there an image built out of this PR (I think even 3 might be there already - one per commit).

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/13)* status: all files reviewed, 2 unresolved discussions (waiting on @alinetskyi and @ysv)

___
*[`VERSION` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/13#-NC-bbdnC6xiLckmNUsv:-NC-bbdo3ZIw7IeF_mFH:bqpr4ac) ([raw file](https://github.com/coreumfoundation/faucet/blob/daca6a2ae4ecb890bec6ac8477953e23fdd26e90/VERSION#L1)):*
> ```
> 0.0.1
> ```

non-blocking
you can add an empty line to the end of this file so that github will not complain

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/13)* status: all files reviewed, 1 unresolved discussion (waiting on @alinetskyi and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/13)* status: all files reviewed, 1 unresolved discussion (waiting on @alinetskyi)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alinetskyi)

**Pull request merged**
