### PR TITLE
Upgrade Coreum to v4 and fix security vulnerabilities

### PR DESCRIPTION
**Pull request by masihyeganeh**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)

### CODE REVIEW

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu, @miladz68, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: 2 of 15 files reviewed, 2 unresolved discussions (waiting on @keyleu, @masihyeganeh, @miladz68, and @ysv)

___
*[`app/gen_mnemonic_and_fund.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJGtTL5mcbnGvVkKLF:-NwJGs4_B5Ok2ed3vMjo:bd1yn70) ([raw file](https://github.com/CoreumFoundation/faucet/blob/7ab0289957d12b3fdda7b3ed012b878740565d4e/app/gen_mnemonic_and_fund.go#L21)):*
> ```Go
> // GenMnemonicAndFund generates a private key and funds it.
> func (a App) GenMnemonicAndFund(ctx context.Context) (GenMnemonicAndFundResult, error) {
> 	kr := a.clientCtx.Keyring()
> ```

The idea of the func is to generate mnemonic for the user, so you don't need to include it into `clientCtx.Keyring`.
___
*[`integration-tests/transfer_test.go` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJ61O0-tbQRUTwH_Gz:-NwJ61O0-tbQRUTwH_H-:b9akgrw) ([raw file](https://github.com/CoreumFoundation/faucet/blob/dacc718680da7c9050e7cefaa40cebbec9f50ff2/integration-tests/transfer_test.go#L63)):*
> ```Go
> 
> func TestTransferRequest(t *testing.T) {
> 	t.Parallel()
> ```

Why did you remove the parallel?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: 2 of 15 files reviewed, 4 unresolved discussions (waiting on @keyleu, @masihyeganeh, @miladz68, and @ysv)

___
*[`main.go` line 79 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJVmAzBc-enct5Je3t:-NwJVmAzBc-enct5Je3u:byonx9n) ([raw file](https://github.com/CoreumFoundation/faucet/blob/7ab0289957d12b3fdda7b3ed012b878740565d4e/main.go#L79)):*
> ```Go
> 	network.SetSDKConfig()
> 
> 	interfaceRegistry := types.NewInterfaceRegistry()
> ```

What is the reason for it? Did you check how we register the client in the coreum integration tests, here it should be done same way?
___
*[`main.go` line 85 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJVVKr9wn6dOSaCLvc:-NwJVVKr9wn6dOSaCLvd:b-r66z3p) ([raw file](https://github.com/CoreumFoundation/faucet/blob/7ab0289957d12b3fdda7b3ed012b878740565d4e/main.go#L85)):*
> ```Go
> 		WithChainID(string(network.ChainID())).
> 		WithBroadcastMode(flags.BroadcastSync).
> 		WithCodec(codec.NewProtoCodec(interfaceRegistry))
> ```

@miladz68 Don't we need to add with AwaitTx here as well ?
___
*[`app/gen_mnemonic_and_fund.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJGtTL5mcbnGvVkKLF:-NwJWD7WC3MqYKJxPjjm:bpmzw9o) ([raw file](https://github.com/CoreumFoundation/faucet/blob/7ab0289957d12b3fdda7b3ed012b878740565d4e/app/gen_mnemonic_and_fund.go#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The idea of the func is to generate mnemonic for the user, so you don't need to include it into `clientCtx.Keyring`.
</blockquote></details>

So you don'y need to pass ` New(clientCtx client.Context...)`

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: 2 of 15 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

___
*[`main.go` line 79 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJVmAzBc-enct5Je3t:-NwK4j0406HIO641NzeE:b-3jur8) ([raw file](https://github.com/CoreumFoundation/faucet/blob/7ab0289957d12b3fdda7b3ed012b878740565d4e/main.go#L79)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the reason for it? Did you check how we register the client in the coreum integration tests, here it should be done same way?
</blockquote></details>

I'm pretty sure that you are doing the same thing but with better structure that doesn't exist here. Please show me to the line of code in coreum that you are talking about if I'm wrong
___
*[`app/gen_mnemonic_and_fund.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJGtTL5mcbnGvVkKLF:-NwK38jq0gzdi2zCFs-H:b5sbgi1) ([raw file](https://github.com/CoreumFoundation/faucet/blob/7ab0289957d12b3fdda7b3ed012b878740565d4e/app/gen_mnemonic_and_fund.go#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

So you don'y need to pass ` New(clientCtx client.Context...)`
</blockquote></details>

Done.

It still needs the codec, so I need to pass clientCtx. Let me know if you insist on not passing it and instantiating new codec here
___
*[`integration-tests/transfer_test.go` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJ61O0-tbQRUTwH_Gz:-NwK3MlNEwuV7bCIH4l1:b-7kttrt) ([raw file](https://github.com/CoreumFoundation/faucet/blob/dacc718680da7c9050e7cefaa40cebbec9f50ff2/integration-tests/transfer_test.go#L63)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why did you remove the parallel?
</blockquote></details>

Tests won't pass in parallel, because of race condition in querying the sequence numbers and sending them. Let me know if having the WithAwaitTx will fix the problem

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: 2 of 15 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

___
*[`main.go` line 85 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJVVKr9wn6dOSaCLvc:-NwKV3U2EyRXY3nLD6MQ:b-896fix) ([raw file](https://github.com/CoreumFoundation/faucet/blob/7ab0289957d12b3fdda7b3ed012b878740565d4e/main.go#L85)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@miladz68 Don't we need to add with AwaitTx here as well ?
</blockquote></details>

Done.
___
*[`integration-tests/transfer_test.go` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJ61O0-tbQRUTwH_Gz:-NwKV8N19_Ik0txnUN0V:b-qjb9o1) ([raw file](https://github.com/CoreumFoundation/faucet/blob/dacc718680da7c9050e7cefaa40cebbec9f50ff2/integration-tests/transfer_test.go#L63)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Tests won't pass in parallel, because of race condition in querying the sequence numbers and sending them. Let me know if having the WithAwaitTx will fix the problem
</blockquote></details>

Reverted the change. Tests are now run in parallel

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: 2 of 15 files reviewed, 1 unresolved discussion (waiting on @keyleu, @masihyeganeh, @miladz68, and @ysv)

___
*[`main.go` line 79 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJVmAzBc-enct5Je3t:-NwOB10N5-avngvM42ZS:b-9g4lx5) ([raw file](https://github.com/CoreumFoundation/faucet/blob/7ab0289957d12b3fdda7b3ed012b878740565d4e/main.go#L79)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I'm pretty sure that you are doing the same thing but with better structure that doesn't exist here. Please show me to the line of code in coreum that you are talking about if I'm wrong
</blockquote></details>

You can use `config.NewEncodingConfig` to do it.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: 2 of 15 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

___
*[`main.go` line 79 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJVmAzBc-enct5Je3t:-NwOMd-EC057wOBRkjFa:b-vrobnt) ([raw file](https://github.com/CoreumFoundation/faucet/blob/7ab0289957d12b3fdda7b3ed012b878740565d4e/main.go#L79)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You can use `config.NewEncodingConfig` to do it.
</blockquote></details>

There is no `config.NewEncodingConfig` in this project. So, I either need to import coreum here for this function call (which I'm not sure is the right call), or I need to mimic the minimum amount of what that does here. I chose option 2, which adds these 2 lines of codes. Let me know if you prefer the first option

**Review by miladz68 — DISMISSED** [review]
> Reviewed 2 of 13 files at r1, 10 of 13 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, and @ysv)

___
*[`main.go` line 85 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJVVKr9wn6dOSaCLvc:-NwOZz2i4hvGiS_Blt0a:b4c9lyr) ([raw file](https://github.com/CoreumFoundation/faucet/blob/7ab0289957d12b3fdda7b3ed012b878740565d4e/main.go#L85)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:thumbsup:

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: 10 of 15 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

___
*[`main.go` line 79 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJVmAzBc-enct5Je3t:-NwOjoDsDcbER6tQWSO9:bv25rsx) ([raw file](https://github.com/CoreumFoundation/faucet/blob/7ab0289957d12b3fdda7b3ed012b878740565d4e/main.go#L79)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

There is no `config.NewEncodingConfig` in this project. So, I either need to import coreum here for this function call (which I'm not sure is the right call), or I need to mimic the minimum amount of what that does here. I chose option 2, which adds these 2 lines of codes. Let me know if you prefer the first option
</blockquote></details>

Just saw that we already have coreum as a dependency. I'll change my code

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 5 of 13 files at r2, 2 of 3 files at r3, 1 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @masihyeganeh, and @ysv)

___
*[`client/coreum/batch_test.go` line 52 at r5](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwPoRR5-Blg7PZ75FqH:-NwPoRR5-Blg7PZ75FqI:b-2y506o) ([raw file](https://github.com/CoreumFoundation/faucet/blob/03f78ea9d2cb061ee0d15b1774a7bce09b67b711/client/coreum/batch_test.go#L52)):*
> ```Go
> 	fundingAddresses := []sdk.AccAddress{}
> 	for i := 0; i < 2; i++ {
> 		address, err := sdk.AccAddressFromHexUnsafe(secp256k1.GenPrivKey().PubKey().Address().String())
> ```

Why do you need this?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @masihyeganeh, and @ysv)

___
*[`main.go` line 79 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJVmAzBc-enct5Je3t:-NwPop4s4B3-808bQiNM:b-z4ggfh) ([raw file](https://github.com/CoreumFoundation/faucet/blob/7ab0289957d12b3fdda7b3ed012b878740565d4e/main.go#L79)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Just saw that we already have coreum as a dependency. I'll change my code
</blockquote></details>

So are you done with the changes?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, and @ysv)

___
*[`main.go` line 79 at r2](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwJVmAzBc-enct5Je3t:-NwPpd0r9v5gSjeNcbd2:bfuyy15) ([raw file](https://github.com/CoreumFoundation/faucet/blob/7ab0289957d12b3fdda7b3ed012b878740565d4e/main.go#L79)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

So are you done with the changes?
</blockquote></details>

Yes. Do they look correct now?
___
*[`client/coreum/batch_test.go` line 52 at r5](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwPoRR5-Blg7PZ75FqH:-NwPpqnz9ysh7dz1AcQK:b-onhjaf) ([raw file](https://github.com/CoreumFoundation/faucet/blob/03f78ea9d2cb061ee0d15b1774a7bce09b67b711/client/coreum/batch_test.go#L52)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need this?
</blockquote></details>

I don't need it. Just the test wouldn't pass otherwise

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1, 5 of 13 files at r2, 2 of 3 files at r3, 1 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @keyleu, and @masihyeganeh)

___
*[`go.mod` line 5 at r5](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwQ8U86AO-QCuKYBtcs:-NwQ8U875v1LxOJpkT6_:brldesp) ([raw file](https://github.com/CoreumFoundation/faucet/blob/03f78ea9d2cb061ee0d15b1774a7bce09b67b711/go.mod#L5)):*
> ```XML
> go 1.21
> 
> toolchain go1.22.1
> ```

I see this `toolchain go` is added in some repos but not inside all of them.
Is there a specific reason for this ?
___
*[`main.go` line 29 at r5](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwQBD4fDDuH4uJEpD8k:-NwQBD4fDDuH4uJEpD8l:bbbvwv3) ([raw file](https://github.com/CoreumFoundation/faucet/blob/03f78ea9d2cb061ee0d15b1774a7bce09b67b711/main.go#L29)):*
> ```Go
> 	coreumconfig "github.com/CoreumFoundation/coreum/v4/pkg/config"
> 	"github.com/CoreumFoundation/coreum/v4/pkg/config/constant"
> 	coreumkeyring "github.com/CoreumFoundation/coreum/v4/pkg/keyring"
> ```

nit: since you migrate to v4 would be nice to mention this in commit title

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @keyleu, and @ysv)

___
*[`go.mod` line 5 at r5](https://reviewable.io/reviews/CoreumFoundation/faucet/81#-NwQ8U86AO-QCuKYBtcs:-NwccVTA94Y4PfbfD5kR:b-2lsmgm) ([raw file](https://github.com/CoreumFoundation/faucet/blob/03f78ea9d2cb061ee0d15b1774a7bce09b67b711/go.mod#L5)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see this `toolchain go` is added in some repos but not inside all of them.
Is there a specific reason for this ?
</blockquote></details>

I don't see a good reason to use specific toolchain version here, because all of our projects should use the same toolchain as our build tools.
It was there before my change and I'd like to know what was the reason

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu and @ysv)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu)

**Review by keyleu — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Review by ysv — APPROVED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/faucet/81)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Pull request merged**
